/**
 * The `.alcove.key` file: one schema and one serializer every application that
 * reads or writes the file uses.
 */

import { z } from "zod";

import { SHARED_SECRET_REGEX } from "./connection";

/** Contents of a `.alcove.key` file. */
export interface KeyFile {
  /** Shared secret; injected into the connection config at runtime. */
  sharedSecret: string;
  /** ISO 8601 datetime after which the shared secret should be considered expired. */
  expires?: string;
  /**
   * ISO 8601 datetime a key exchange began at that has not yet saved its rotated
   * secret. Written just before the key exchange starts and dropped by the write
   * that stores the rotated secret, so a file still holding it at the next run
   * records a rotation that may have completed on the partner's side only.
   */
  rotationInFlightSince?: string;
  /**
   * ISO 8601 datetime the secret this file holds was rotated to, when a relay
   * registrar has not yet confirmed that it holds the relay key derived from
   * that secret. Written by the rotation itself and dropped once the registrar
   * confirms, so a file still holding it at the next run records a
   * registration that run retries before it dials.
   */
  relayRegistrationPendingSince?: string;
}

/** The rule a key file's `sharedSecret` is held to, stated without its value. */
export const KEY_FILE_SHARED_SECRET_FORMAT_MESSAGE =
  "sharedSecret must be a base64url-encoded 32-byte value (43 base64url " +
  "characters; final character must be in [AEIMQUYcgkosw048])";

/**
 * Each key-file field's own schema, for a document that embeds some of the
 * fields under a stricter policy of its own.
 */
export const KEY_FILE_FIELD_SCHEMAS = {
  sharedSecret: z
    .string()
    .regex(
      SHARED_SECRET_REGEX,
      KEY_FILE_SHARED_SECRET_FORMAT_MESSAGE +
        "; shared secrets are generated by 'alcove invite' - to obtain a new " +
        "one, both parties must re-invite",
    ),
  expires: z.iso.datetime().optional(),
  rotationInFlightSince: z.iso.datetime().optional(),
  relayRegistrationPendingSince: z.iso.datetime().optional(),
} as const;

/** The key file's validator. A field outside {@link KeyFile} is dropped. */
export const KeyFileSchema: z.ZodType<KeyFile> = z.object(
  KEY_FILE_FIELD_SCHEMAS,
);

const KEY_FILE_FIELD_NAMES: ReadonlySet<string> = new Set(
  Object.keys(KEY_FILE_FIELD_SCHEMAS),
);

/**
 * The names of the top-level fields of a parsed key file that
 * {@link KeyFileSchema} does not read and so drops, in the file's order, for a
 * reader to name to the operator. Returns names only: a value may be the
 * secret. Empty for anything other than a plain object.
 */
export function keyFileUnreadFieldNames(document: unknown): Array<string> {
  if (typeof document !== "object" || document === null) return [];
  if (Array.isArray(document)) return [];
  return Object.keys(document).filter(
    (name) => !KEY_FILE_FIELD_NAMES.has(name),
  );
}

/**
 * The bytes of a `.alcove.key` holding `data`: pretty-printed JSON with a
 * trailing newline, holding only the {@link KeyFile} fields `data` sets.
 * Validates nothing; a writer checks the secret's shape itself.
 */
export function serializeKeyFile(data: KeyFile): string {
  const known = Object.fromEntries(
    Object.entries(data).filter(([name]) => KEY_FILE_FIELD_NAMES.has(name)),
  );
  return JSON.stringify(known, null, 2) + "\n";
}
