/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptRouteImport } from './routes/accept'
import { Route as BenchRouteRouteImport } from './routes/bench/route'
import { Route as DirectRouteImport } from './routes/direct'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as RelayRouteImport } from './routes/relay'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as BenchIndexRouteImport } from './routes/bench/index'
import { Route as BenchAcceptRouteImport } from './routes/bench/accept'
import { Route as BenchExchangeRouteImport } from './routes/bench/exchange'
import { Route as BenchVerifyRouteImport } from './routes/bench/verify'
import { Route as SavedIndexRouteImport } from './routes/saved.index'
import { Route as SavedIdRouteImport } from './routes/saved.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptRoute = AcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRouteRoute = BenchRouteRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectRoute = DirectRouteImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayRoute = RelayRouteImport.update({
  id: '/relay',
  path: '/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchIndexRoute = BenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BenchRouteRoute,
} as any)
const BenchAcceptRoute = BenchAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => BenchRouteRoute,
} as any)
const BenchExchangeRoute = BenchExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => BenchRouteRoute,
} as any)
const BenchVerifyRoute = BenchVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => BenchRouteRoute,
} as any)
const SavedIndexRoute = SavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedIdRoute = SavedIdRouteImport.update({
  id: '/saved/$id',
  path: '/saved/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof BenchRouteRouteWithChildren
  '/accept': typeof AcceptRoute
  '/direct': typeof DirectRoute
  '/exchange': typeof ExchangeRoute
  '/quick': typeof QuickRoute
  '/relay': typeof RelayRoute
  '/verify': typeof VerifyRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/saved/$id': typeof SavedIdRoute
  '/bench/': typeof BenchIndexRoute
  '/saved/': typeof SavedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/direct': typeof DirectRoute
  '/exchange': typeof ExchangeRoute
  '/quick': typeof QuickRoute
  '/relay': typeof RelayRoute
  '/verify': typeof VerifyRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/saved/$id': typeof SavedIdRoute
  '/bench': typeof BenchIndexRoute
  '/saved': typeof SavedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bench': typeof BenchRouteRouteWithChildren
  '/accept': typeof AcceptRoute
  '/direct': typeof DirectRoute
  '/exchange': typeof ExchangeRoute
  '/quick': typeof QuickRoute
  '/relay': typeof RelayRoute
  '/verify': typeof VerifyRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/saved/$id': typeof SavedIdRoute
  '/bench/': typeof BenchIndexRoute
  '/saved/': typeof SavedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bench'
    | '/accept'
    | '/direct'
    | '/exchange'
    | '/quick'
    | '/relay'
    | '/verify'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/saved/$id'
    | '/bench/'
    | '/saved/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept'
    | '/direct'
    | '/exchange'
    | '/quick'
    | '/relay'
    | '/verify'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/saved/$id'
    | '/bench'
    | '/saved'
  id:
    | '__root__'
    | '/'
    | '/bench'
    | '/accept'
    | '/direct'
    | '/exchange'
    | '/quick'
    | '/relay'
    | '/verify'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/saved/$id'
    | '/bench/'
    | '/saved/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchRouteRoute: typeof BenchRouteRouteWithChildren
  AcceptRoute: typeof AcceptRoute
  DirectRoute: typeof DirectRoute
  ExchangeRoute: typeof ExchangeRoute
  QuickRoute: typeof QuickRoute
  RelayRoute: typeof RelayRoute
  VerifyRoute: typeof VerifyRoute
  SavedIdRoute: typeof SavedIdRoute
  SavedIndexRoute: typeof SavedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept': {
      id: '/accept'
      path: '/accept'
      fullPath: '/accept'
      preLoaderRoute: typeof AcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direct': {
      id: '/direct'
      path: '/direct'
      fullPath: '/direct'
      preLoaderRoute: typeof DirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relay': {
      id: '/relay'
      path: '/relay'
      fullPath: '/relay'
      preLoaderRoute: typeof RelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench/': {
      id: '/bench/'
      path: '/'
      fullPath: '/bench/'
      preLoaderRoute: typeof BenchIndexRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/bench/accept': {
      id: '/bench/accept'
      path: '/accept'
      fullPath: '/bench/accept'
      preLoaderRoute: typeof BenchAcceptRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/bench/exchange': {
      id: '/bench/exchange'
      path: '/exchange'
      fullPath: '/bench/exchange'
      preLoaderRoute: typeof BenchExchangeRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/bench/verify': {
      id: '/bench/verify'
      path: '/verify'
      fullPath: '/bench/verify'
      preLoaderRoute: typeof BenchVerifyRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/saved/': {
      id: '/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof SavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/$id': {
      id: '/saved/$id'
      path: '/saved/$id'
      fullPath: '/saved/$id'
      preLoaderRoute: typeof SavedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BenchRouteRouteChildren {
  BenchAcceptRoute: typeof BenchAcceptRoute
  BenchExchangeRoute: typeof BenchExchangeRoute
  BenchVerifyRoute: typeof BenchVerifyRoute
  BenchIndexRoute: typeof BenchIndexRoute
}

const BenchRouteRouteChildren: BenchRouteRouteChildren = {
  BenchAcceptRoute: BenchAcceptRoute,
  BenchExchangeRoute: BenchExchangeRoute,
  BenchVerifyRoute: BenchVerifyRoute,
  BenchIndexRoute: BenchIndexRoute,
}

const BenchRouteRouteWithChildren = BenchRouteRoute._addFileChildren(
  BenchRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchRouteRoute: BenchRouteRouteWithChildren,
  AcceptRoute: AcceptRoute,
  DirectRoute: DirectRoute,
  ExchangeRoute: ExchangeRoute,
  QuickRoute: QuickRoute,
  RelayRoute: RelayRoute,
  VerifyRoute: VerifyRoute,
  SavedIdRoute: SavedIdRoute,
  SavedIndexRoute: SavedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
